version: "3.8"
services:
  mongo:
    image: mongo
    restart: always
    networks:
      - mongo
    ports:
      - 27017:27017
    environment:
      #MONGO_INITDB_DATABASE: shorter
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-test:
    image: mongo
    restart: always
    networks:
      - mongo
    ports:
      - 27018:27017
    environment:
      #MONGO_INITDB_DATABASE: shorter
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - mongo
    ports:
      - 8085:8081
    environment:
      #ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
     # ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017
networks:
  mongo:
    driver: bridge
